# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wea_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1507, 909)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_whole = QtWidgets.QFrame(self.centralwidget)
        self.frame_whole.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_whole.setStyleSheet("#frame{\n"
"    border-radius:30px\n"
"}")
        self.frame_whole.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_whole.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_whole.setObjectName("frame_whole")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_whole)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_up = QtWidgets.QFrame(self.frame_whole)
        self.frame_up.setMaximumSize(QtCore.QSize(16777215, 55))
        self.frame_up.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(77, 77, 85);\n"
"    border-top-left-radius:30px;\n"
"    border-top-right-radius:30px;\n"
"}")
        self.frame_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_up.setObjectName("frame_up")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_up)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_title = QtWidgets.QFrame(self.frame_up)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_title.sizePolicy().hasHeightForWidth())
        self.frame_title.setSizePolicy(sizePolicy)
        self.frame_title.setMinimumSize(QtCore.QSize(1160, 0))
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.pushButton = QtWidgets.QPushButton(self.frame_title)
        self.pushButton.setGeometry(QtCore.QRect(20, 5, 45, 45))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    \n"
"    border-image: url(:/images/icons/PyDracula.png);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_title)
        self.textBrowser.setGeometry(QtCore.QRect(70, 10, 291, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_4.addWidget(self.frame_title)
        self.frame_right_top = QtWidgets.QFrame(self.frame_up)
        self.frame_right_top.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_right_top.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_right_top.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.frame_right_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right_top.setObjectName("frame_right_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_right_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Button_big = QtWidgets.QPushButton(self.frame_right_top)
        self.Button_big.setMaximumSize(QtCore.QSize(25, 25))
        self.Button_big.setStyleSheet("")
        self.Button_big.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons/fangda.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Button_big.setIcon(icon)
        self.Button_big.setObjectName("Button_big")
        self.horizontalLayout_3.addWidget(self.Button_big)
        self.Button_normal = QtWidgets.QPushButton(self.frame_right_top)
        self.Button_normal.setMaximumSize(QtCore.QSize(25, 25))
        self.Button_normal.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/icons/normal.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Button_normal.setIcon(icon1)
        self.Button_normal.setObjectName("Button_normal")
        self.horizontalLayout_3.addWidget(self.Button_normal)
        self.Button_small = QtWidgets.QPushButton(self.frame_right_top)
        self.Button_small.setMaximumSize(QtCore.QSize(25, 25))
        self.Button_small.setStyleSheet("")
        self.Button_small.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/icons/jian.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Button_small.setIcon(icon2)
        self.Button_small.setObjectName("Button_small")
        self.horizontalLayout_3.addWidget(self.Button_small)
        self.Button_exit = QtWidgets.QPushButton(self.frame_right_top)
        self.Button_exit.setMaximumSize(QtCore.QSize(25, 25))
        self.Button_exit.setStyleSheet("")
        self.Button_exit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Button_exit.setIcon(icon3)
        self.Button_exit.setObjectName("Button_exit")
        self.horizontalLayout_3.addWidget(self.Button_exit)
        self.horizontalLayout_4.addWidget(self.frame_right_top)
        self.verticalLayout.addWidget(self.frame_up)
        self.frame_content = QtWidgets.QFrame(self.frame_whole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_content.sizePolicy().hasHeightForWidth())
        self.frame_content.setSizePolicy(sizePolicy)
        self.frame_content.setStyleSheet("")
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left = QtWidgets.QFrame(self.frame_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left.sizePolicy().hasHeightForWidth())
        self.frame_left.setSizePolicy(sizePolicy)
        self.frame_left.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_left.setStyleSheet("#frame_left{\n"
"    background-image: url(:/images/icons/black.png);\n"
"}")
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fra_lup = QtWidgets.QFrame(self.frame_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.fra_lup.sizePolicy().hasHeightForWidth())
        self.fra_lup.setSizePolicy(sizePolicy)
        self.fra_lup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fra_lup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fra_lup.setObjectName("fra_lup")
        self.choose = QtWidgets.QLabel(self.fra_lup)
        self.choose.setGeometry(QtCore.QRect(15, 55, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.choose.setFont(font)
        self.choose.setStyleSheet("QLabel{\n"
"    background: rgb(0, 0, 0, 0);\n"
"    color: rgb(208, 208, 211);\n"
"}")
        self.choose.setObjectName("choose")
        self.comboBox = QtWidgets.QComboBox(self.fra_lup)
        self.comboBox.setGeometry(QtCore.QRect(110, 60, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox{\n"
"    border-radius:8px;\n"
"    background:rgba(239, 239, 239, 175);\n"
"    padding-left:15px;\n"
"    color: rgb(129, 86, 120);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.setting = QtWidgets.QLabel(self.fra_lup)
        self.setting.setGeometry(QtCore.QRect(50, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.setting.setFont(font)
        self.setting.setStyleSheet("QLabel{\n"
"    background: rgb(0, 0, 0, 0);\n"
"    color: rgb(208, 208, 211);\n"
"}")
        self.setting.setObjectName("setting")
        self.shezhi = QtWidgets.QPushButton(self.fra_lup)
        self.shezhi.setGeometry(QtCore.QRect(18, 10, 31, 31))
        self.shezhi.setStyleSheet("QPushButton{\n"
"    \n"
"    border-image: url(:/images/icons/setting.png);\n"
"}")
        self.shezhi.setText("")
        self.shezhi.setObjectName("shezhi")
        self.verticalLayout_6.addWidget(self.fra_lup)
        self.fra_lmiddle = QtWidgets.QFrame(self.frame_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.fra_lmiddle.sizePolicy().hasHeightForWidth())
        self.fra_lmiddle.setSizePolicy(sizePolicy)
        self.fra_lmiddle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fra_lmiddle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fra_lmiddle.setObjectName("fra_lmiddle")
        self.input = QtWidgets.QLabel(self.fra_lmiddle)
        self.input.setGeometry(QtCore.QRect(15, -3, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input.setFont(font)
        self.input.setStyleSheet("QLabel{\n"
"    background: rgb(0, 0, 0, 0);\n"
"    color: rgb(208, 208, 211);\n"
"}")
        self.input.setObjectName("input")
        self.pic = QtWidgets.QPushButton(self.fra_lmiddle)
        self.pic.setGeometry(QtCore.QRect(25, 40, 40, 40))
        self.pic.setStyleSheet("QPushButton{\n"
"    border-image: url(:/images/icons/picture.png);\n"
"}")
        self.pic.setText("")
        self.pic.setObjectName("pic")
        self.video = QtWidgets.QPushButton(self.fra_lmiddle)
        self.video.setGeometry(QtCore.QRect(25, 95, 40, 40))
        self.video.setStyleSheet("QPushButton{\n"
"    border-image: url(:/images/icons/video.png);\n"
"}\n"
"")
        self.video.setText("")
        self.video.setObjectName("video")
        self.camera = QtWidgets.QPushButton(self.fra_lmiddle)
        self.camera.setGeometry(QtCore.QRect(25, 150, 40, 40))
        self.camera.setStyleSheet("QPushButton{\n"
"    \n"
"    border-image: url(:/images/icons/camera.png);\n"
"}")
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.Button_pic = QtWidgets.QPushButton(self.fra_lmiddle)
        self.Button_pic.setGeometry(QtCore.QRect(90, 40, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button_pic.setFont(font)
        self.Button_pic.setStyleSheet("QPushButton{\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(55, 90, 164, 165), stop:1 rgba(221, 117, 161, 165));\n"
"    border-radius:7px;\n"
"    color: rgb(208, 208, 211);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Button_pic.setIconSize(QtCore.QSize(22, 22))
        self.Button_pic.setObjectName("Button_pic")
        self.Button_camera = QtWidgets.QPushButton(self.fra_lmiddle)
        self.Button_camera.setGeometry(QtCore.QRect(90, 150, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button_camera.setFont(font)
        self.Button_camera.setStyleSheet("QPushButton{\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(55, 90, 164, 165), stop:1 rgba(221, 117, 161, 165));\n"
"    border-radius:7px;\n"
"    color: rgb(208, 208, 211);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Button_camera.setIconSize(QtCore.QSize(22, 22))
        self.Button_camera.setAutoRepeatInterval(100)
        self.Button_camera.setObjectName("Button_camera")
        self.Button_video = QtWidgets.QPushButton(self.fra_lmiddle)
        self.Button_video.setGeometry(QtCore.QRect(90, 95, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Button_video.setFont(font)
        self.Button_video.setStyleSheet("QPushButton{\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(55, 90, 164, 165), stop:1 rgba(221, 117, 161, 165));\n"
"    border-radius:7px;\n"
"    color: rgb(208, 208, 211);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Button_video.setIconSize(QtCore.QSize(22, 22))
        self.Button_video.setObjectName("Button_video")
        self.input_2 = QtWidgets.QLabel(self.fra_lmiddle)
        self.input_2.setGeometry(QtCore.QRect(15, 195, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_2.setFont(font)
        self.input_2.setStyleSheet("QLabel{\n"
"    background: rgb(0, 0, 0, 0);\n"
"    color: rgb(208, 208, 211);\n"
"}")
        self.input_2.setObjectName("input_2")
        self.ConfSpinBox = QtWidgets.QDoubleSpinBox(self.fra_lmiddle)
        self.ConfSpinBox.setGeometry(QtCore.QRect(15, 235, 51, 31))
        self.ConfSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"    border-radius: 5px;\n"
"}\n"
"QDoubleSpinBox::up-button {\n"
"    image: url(:/images/icons/arrow-up.png);\n"
"    border-radius: 50px;\n"
"}\n"
"QDoubleSpinBox::down-button {\n"
"    image: url(:/images/icons/arrow-down.png);\n"
"    border-radius: 50px;\n"
"}")
        self.ConfSpinBox.setObjectName("ConfSpinBox")
        self.ConfSlider = QtWidgets.QSlider(self.fra_lmiddle)
        self.ConfSlider.setGeometry(QtCore.QRect(100, 240, 181, 22))
        self.ConfSlider.setStyleSheet("/*horizontal ：水平QSlider*/\n"
"QSlider::groove:horizontal {\n"
"    border: 0px solid #bbb;\n"
"}\n"
"\n"
"/*1.滑动过的槽设计参数*/\n"
"QSlider::sub-page:horizontal {\n"
"     /*槽颜色*/\n"
"    background: #f0a732;\n"
"     /*外环区域倒圆角度*/\n"
"    border-radius: 2px;\n"
"     /*上遮住区域高度*/\n"
"    margin-top:8px;\n"
"     /*下遮住区域高度*/\n"
"    margin-bottom:8px;\n"
"}\n"
"\n"
"/*2.未滑动过的槽设计参数*/\n"
"QSlider::add-page:horizontal {\n"
"    /*槽颜色*/\n"
"    background: rgb(105,105, 105);\n"
"   \n"
"    border: 1px solid #777;\n"
"    /*外环区域倒圆角度*/\n"
"    border-radius: 2px;\n"
"     /*上遮住区域高度*/\n"
"    margin-top:8px;\n"
"     /*下遮住区域高度*/\n"
"    margin-bottom:8px;\n"
"}\n"
"\n"
"/*3.平时滑动的滑块设计参数*/\n"
"QSlider::handle:horizontal {\n"
"    /*滑块颜色*/\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(55, 90, 164, 225), stop:1 rgba(221, 117, 161, 225));\n"
"    /*滑块的宽度*/\n"
"    width:12px;\n"
"\n"
"    /*滑块外环为1px，再加颜色*/\n"
"    border: 1px solid rgb(193,204,208);\n"
"\n"
"     /*滑块外环倒圆角度*/\n"
"    border-radius: 15px;\n"
"     /*上遮住区域高度*/\n"
"    margin-top:2px;\n"
"     /*下遮住区域高度*/\n"
"    margin-bottom:2px;\n"
"}\n"
"\n"
"/*4.手动拉动时显示的滑块设计参数*/\n"
"QSlider::handle:horizontal:hover {\n"
"    /*滑块颜色*/\n"
"    background: #484848;\n"
"    /*滑块的宽度*/\n"
"    width: 12px;\n"
"    \n"
"    border: 1px solid #484848;\n"
"     /*滑块外环倒圆角度*/\n"
"    border-radius: 15px;\n"
"     /*上遮住区域高度*/\n"
"    margin-top:2px;\n"
"     /*下遮住区域高度*/\n"
"    margin-bottom:2px;\n"
"}\n"
"\n"
"")
        self.ConfSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ConfSlider.setObjectName("ConfSlider")
        self.input_3 = QtWidgets.QLabel(self.fra_lmiddle)
        self.input_3.setGeometry(QtCore.QRect(15, 270, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.input_3.setFont(font)
        self.input_3.setStyleSheet("QLabel{\n"
"    background: rgb(0, 0, 0, 0);\n"
"    color: rgb(208, 208, 211);\n"
"}")
        self.input_3.setObjectName("input_3")
        self.IouSpinBox = QtWidgets.QDoubleSpinBox(self.fra_lmiddle)
        self.IouSpinBox.setGeometry(QtCore.QRect(15, 310, 51, 31))
        self.IouSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"    border-radius: 5px;\n"
"}\n"
"QDoubleSpinBox::up-button {\n"
"    image: url(:/images/icons/arrow-up.png);\n"
"    border-radius: 50px;\n"
"}\n"
"QDoubleSpinBox::down-button {\n"
"    image: url(:/images/icons/arrow-down.png);\n"
"    border-radius: 50px;\n"
"}")
        self.IouSpinBox.setObjectName("IouSpinBox")
        self.IouSlider = QtWidgets.QSlider(self.fra_lmiddle)
        self.IouSlider.setGeometry(QtCore.QRect(100, 315, 181, 22))
        self.IouSlider.setStyleSheet("/*horizontal ：水平QSlider*/\n"
"QSlider::groove:horizontal {\n"
"    border: 0px solid #bbb;\n"
"}\n"
"\n"
"/*1.滑动过的槽设计参数*/\n"
"QSlider::sub-page:horizontal {\n"
"     /*槽颜色*/\n"
"    background: #f0a732;\n"
"     /*外环区域倒圆角度*/\n"
"    border-radius: 2px;\n"
"     /*上遮住区域高度*/\n"
"    margin-top:8px;\n"
"     /*下遮住区域高度*/\n"
"    margin-bottom:8px;\n"
"}\n"
"\n"
"/*2.未滑动过的槽设计参数*/\n"
"QSlider::add-page:horizontal {\n"
"    /*槽颜色*/\n"
"    background: rgb(105,105, 105);\n"
"   \n"
"    border: 1px solid #777;\n"
"    /*外环区域倒圆角度*/\n"
"    border-radius: 2px;\n"
"     /*上遮住区域高度*/\n"
"    margin-top:8px;\n"
"     /*下遮住区域高度*/\n"
"    margin-bottom:8px;\n"
"}\n"
"\n"
"/*3.平时滑动的滑块设计参数*/\n"
"QSlider::handle:horizontal {\n"
"    /*滑块颜色*/\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(55, 90, 164, 225), stop:1 rgba(221, 117, 161, 225));\n"
"    /*滑块的宽度*/\n"
"    width:12px;\n"
"\n"
"    /*滑块外环为1px，再加颜色*/\n"
"    border: 1px solid rgb(193,204,208);\n"
"\n"
"     /*滑块外环倒圆角度*/\n"
"    border-radius: 15px;\n"
"     /*上遮住区域高度*/\n"
"    margin-top:2px;\n"
"     /*下遮住区域高度*/\n"
"    margin-bottom:2px;\n"
"}\n"
"\n"
"/*4.手动拉动时显示的滑块设计参数*/\n"
"QSlider::handle:horizontal:hover {\n"
"    /*滑块颜色*/\n"
"    background: #484848;\n"
"    /*滑块的宽度*/\n"
"    width: 12px;\n"
"    \n"
"    border: 1px solid #484848;\n"
"     /*滑块外环倒圆角度*/\n"
"    border-radius: 15px;\n"
"     /*上遮住区域高度*/\n"
"    margin-top:2px;\n"
"     /*下遮住区域高度*/\n"
"    margin-bottom:2px;\n"
"}\n"
"\n"
"")
        self.IouSlider.setOrientation(QtCore.Qt.Horizontal)
        self.IouSlider.setObjectName("IouSlider")
        self.verticalLayout_6.addWidget(self.fra_lmiddle)
        self.fra_ldown = QtWidgets.QFrame(self.frame_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.fra_ldown.sizePolicy().hasHeightForWidth())
        self.fra_ldown.setSizePolicy(sizePolicy)
        self.fra_ldown.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fra_ldown.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fra_ldown.setObjectName("fra_ldown")
        self.result = QtWidgets.QLabel(self.fra_ldown)
        self.result.setGeometry(QtCore.QRect(15, 0, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setStyleSheet("QLabel{    \n"
"    color: rgb(208, 208, 211);\n"
"    background: rgb(0, 0, 0, 0);\n"
"}")
        self.result.setObjectName("result")
        self.show_result = QtWidgets.QTextBrowser(self.fra_ldown)
        self.show_result.setGeometry(QtCore.QRect(30, 50, 251, 231))
        self.show_result.setStyleSheet("QTextBrowser{\n"
"    background:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(55, 90, 164, 165), stop:1 rgba(221, 117, 161, 165));\n"
"    border-radius:15px;\n"
"    color: rgb(208, 208, 211);\n"
"    padding: 10px;\n"
"    \n"
"}")
        self.show_result.setObjectName("show_result")
        self.verticalLayout_6.addWidget(self.fra_ldown)
        self.horizontalLayout_2.addWidget(self.frame_left)
        self.frame_right = QtWidgets.QFrame(self.frame_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_right.sizePolicy().hasHeightForWidth())
        self.frame_right.setSizePolicy(sizePolicy)
        self.frame_right.setStyleSheet("#frame_right{\n"
"    border-image: url(:/images/icons/black2.png);\n"
"}")
        self.frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_right)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("QWidget{\n"
"    border-radius:30px;\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(55, 90, 164, 55), stop:1 rgba(221, 117, 161, 55));\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_pic = QtWidgets.QWidget()
        self.page_pic.setObjectName("page_pic")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_pic)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.f_pic_up = QtWidgets.QFrame(self.page_pic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.f_pic_up.sizePolicy().hasHeightForWidth())
        self.f_pic_up.setSizePolicy(sizePolicy)
        self.f_pic_up.setStyleSheet("#f_pic_up{\n"
"    background: rgba(0, 0, 0, 0);\n"
"}")
        self.f_pic_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_pic_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_pic_up.setObjectName("f_pic_up")
        self.label = QtWidgets.QLabel(self.f_pic_up)
        self.label.setGeometry(QtCore.QRect(30, 4, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    background: rgb(0, 0, 0, 0);\n"
"    color: rgb(208, 208, 211);\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.f_pic_up)
        self.f_pic_content = QtWidgets.QFrame(self.page_pic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.f_pic_content.sizePolicy().hasHeightForWidth())
        self.f_pic_content.setSizePolicy(sizePolicy)
        self.f_pic_content.setStyleSheet("#f_pic_content{\n"
"    background: rgba(0, 0, 0, 0);\n"
"}")
        self.f_pic_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_pic_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_pic_content.setObjectName("f_pic_content")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.f_pic_content)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.f_pic_left = QtWidgets.QFrame(self.f_pic_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.f_pic_left.sizePolicy().hasHeightForWidth())
        self.f_pic_left.setSizePolicy(sizePolicy)
        self.f_pic_left.setStyleSheet("#f_pic_left{\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border-right:1px solid rgba(255, 255, 255, 120);\n"
"    border-radius:0px;\n"
"}")
        self.f_pic_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_pic_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_pic_left.setObjectName("f_pic_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.f_pic_left)
        self.verticalLayout_3.setContentsMargins(20, 80, 20, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pic_org = QtWidgets.QLabel(self.f_pic_left)
        self.pic_org.setMinimumSize(QtCore.QSize(500, 420))
        self.pic_org.setStyleSheet("background-color: rgb(255, 255, 255, 180);\n"
"padding-left:50px")
        self.pic_org.setText("")
        self.pic_org.setObjectName("pic_org")
        self.verticalLayout_3.addWidget(self.pic_org, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Button_upload = QtWidgets.QPushButton(self.f_pic_left)
        self.Button_upload.setMinimumSize(QtCore.QSize(130, 55))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Button_upload.setFont(font)
        self.Button_upload.setStyleSheet("QPushButton{\n"
"    background: rgb(0, 0, 0, 200);\n"
"    border-radius:7px;\n"
"    color: rgb(208, 208, 211);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Button_upload.setObjectName("Button_upload")
        self.verticalLayout_3.addWidget(self.Button_upload, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addWidget(self.f_pic_left)
        self.f_pic_right = QtWidgets.QFrame(self.f_pic_content)
        self.f_pic_right.setStyleSheet("#f_pic_right{\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border-left:1px solid rgba(255, 255, 255, 120);\n"
"    border-radius:0px;\n"
"}")
        self.f_pic_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_pic_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_pic_right.setObjectName("f_pic_right")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.f_pic_right)
        self.verticalLayout_5.setContentsMargins(20, 80, 20, 10)
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pic_detect = QtWidgets.QLabel(self.f_pic_right)
        self.pic_detect.setMinimumSize(QtCore.QSize(500, 420))
        self.pic_detect.setStyleSheet("background-color: rgb(255, 255, 255, 180);\n"
"padding-left:50px")
        self.pic_detect.setText("")
        self.pic_detect.setObjectName("pic_detect")
        self.verticalLayout_5.addWidget(self.pic_detect, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.Button_detect = QtWidgets.QPushButton(self.f_pic_right)
        self.Button_detect.setMinimumSize(QtCore.QSize(130, 55))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Button_detect.setFont(font)
        self.Button_detect.setStyleSheet("QPushButton{\n"
"    background: rgb(0, 0, 0, 200);\n"
"    border-radius:7px;\n"
"    color: rgb(208, 208, 211);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Button_detect.setObjectName("Button_detect")
        self.verticalLayout_5.addWidget(self.Button_detect, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addWidget(self.f_pic_right)
        self.verticalLayout_4.addWidget(self.f_pic_content)
        self.stackedWidget.addWidget(self.page_pic)
        self.page_video = QtWidgets.QWidget()
        self.page_video.setObjectName("page_video")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_video)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.f_vid_up = QtWidgets.QFrame(self.page_video)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.f_vid_up.sizePolicy().hasHeightForWidth())
        self.f_vid_up.setSizePolicy(sizePolicy)
        self.f_vid_up.setStyleSheet("#f_vid_up{\n"
"    background: rgba(0, 0, 0, 0);\n"
"}")
        self.f_vid_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_vid_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_vid_up.setObjectName("f_vid_up")
        self.label_2 = QtWidgets.QLabel(self.f_vid_up)
        self.label_2.setGeometry(QtCore.QRect(30, 4, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    background: rgb(0, 0, 0, 0);\n"
"    color: rgb(208, 208, 211);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.f_vid_up)
        self.f_vid_content = QtWidgets.QFrame(self.page_video)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.f_vid_content.sizePolicy().hasHeightForWidth())
        self.f_vid_content.setSizePolicy(sizePolicy)
        self.f_vid_content.setStyleSheet("#f_vid_content{\n"
"    background: rgba(0, 0, 0, 0);\n"
"}")
        self.f_vid_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_vid_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_vid_content.setObjectName("f_vid_content")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.f_vid_content)
        self.verticalLayout_8.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.vid_detect = QtWidgets.QLabel(self.f_vid_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.vid_detect.sizePolicy().hasHeightForWidth())
        self.vid_detect.setSizePolicy(sizePolicy)
        self.vid_detect.setMinimumSize(QtCore.QSize(500, 300))
        self.vid_detect.setStyleSheet("background-color: rgb(255, 255, 255, 180);\n"
"padding-left:180px")
        self.vid_detect.setText("")
        self.vid_detect.setObjectName("vid_detect")
        self.verticalLayout_8.addWidget(self.vid_detect)
        self.frame_btn2 = QtWidgets.QFrame(self.f_vid_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_btn2.sizePolicy().hasHeightForWidth())
        self.frame_btn2.setSizePolicy(sizePolicy)
        self.frame_btn2.setStyleSheet("background: rgba(0, 0, 0, 0);")
        self.frame_btn2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btn2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn2.setObjectName("frame_btn2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_btn2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Button_openvid = QtWidgets.QPushButton(self.frame_btn2)
        self.Button_openvid.setMinimumSize(QtCore.QSize(200, 55))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Button_openvid.setFont(font)
        self.Button_openvid.setStyleSheet("QPushButton{\n"
"    background: rgb(0, 0, 0, 200);\n"
"    border-radius:7px;\n"
"    color: rgb(208, 208, 211);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Button_openvid.setObjectName("Button_openvid")
        self.horizontalLayout_7.addWidget(self.Button_openvid, 0, QtCore.Qt.AlignHCenter)
        self.Button_stopv = QtWidgets.QPushButton(self.frame_btn2)
        self.Button_stopv.setMinimumSize(QtCore.QSize(200, 55))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Button_stopv.setFont(font)
        self.Button_stopv.setStyleSheet("QPushButton{\n"
"    background: rgb(0, 0, 0, 200);\n"
"    border-radius:7px;\n"
"    color: rgb(208, 208, 211);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Button_stopv.setObjectName("Button_stopv")
        self.horizontalLayout_7.addWidget(self.Button_stopv, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_8.addWidget(self.frame_btn2)
        self.verticalLayout_7.addWidget(self.f_vid_content)
        self.stackedWidget.addWidget(self.page_video)
        self.page_camera = QtWidgets.QWidget()
        self.page_camera.setObjectName("page_camera")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_camera)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.f_cam_up = QtWidgets.QFrame(self.page_camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.f_cam_up.sizePolicy().hasHeightForWidth())
        self.f_cam_up.setSizePolicy(sizePolicy)
        self.f_cam_up.setStyleSheet("#f_cam_up{\n"
"    background: rgba(0, 0, 0, 0);\n"
"}")
        self.f_cam_up.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_cam_up.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_cam_up.setObjectName("f_cam_up")
        self.label_4 = QtWidgets.QLabel(self.f_cam_up)
        self.label_4.setGeometry(QtCore.QRect(30, 4, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    background: rgb(0, 0, 0, 0);\n"
"    color: rgb(208, 208, 211);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.f_cam_up)
        self.f_cam_content = QtWidgets.QFrame(self.page_camera)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.f_cam_content.sizePolicy().hasHeightForWidth())
        self.f_cam_content.setSizePolicy(sizePolicy)
        self.f_cam_content.setStyleSheet("#f_cam_content{\n"
"    background: rgba(0, 0, 0, 0);\n"
"}\n"
"")
        self.f_cam_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_cam_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_cam_content.setObjectName("f_cam_content")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.f_cam_content)
        self.verticalLayout_10.setContentsMargins(30, -1, 30, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cam_detect = QtWidgets.QLabel(self.f_cam_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.cam_detect.sizePolicy().hasHeightForWidth())
        self.cam_detect.setSizePolicy(sizePolicy)
        self.cam_detect.setMinimumSize(QtCore.QSize(500, 300))
        self.cam_detect.setStyleSheet("background-color: rgb(255, 255, 255, 180);\n"
"padding-left:180px")
        self.cam_detect.setText("")
        self.cam_detect.setObjectName("cam_detect")
        self.verticalLayout_10.addWidget(self.cam_detect)
        self.frame = QtWidgets.QFrame(self.f_cam_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background: rgba(0, 0, 0, 0);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Button_opencam = QtWidgets.QPushButton(self.frame)
        self.Button_opencam.setMinimumSize(QtCore.QSize(200, 55))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Button_opencam.setFont(font)
        self.Button_opencam.setStyleSheet("QPushButton{\n"
"    background: rgb(0, 0, 0, 200);\n"
"    border-radius:7px;\n"
"    color: rgb(208, 208, 211);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Button_opencam.setObjectName("Button_opencam")
        self.horizontalLayout_6.addWidget(self.Button_opencam, 0, QtCore.Qt.AlignHCenter)
        self.Button_stopc = QtWidgets.QPushButton(self.frame)
        self.Button_stopc.setMinimumSize(QtCore.QSize(200, 55))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Button_stopc.setFont(font)
        self.Button_stopc.setStyleSheet("QPushButton{\n"
"    background: rgb(0, 0, 0, 200);\n"
"    border-radius:7px;\n"
"    color: rgb(208, 208, 211);\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.Button_stopc.setObjectName("Button_stopc")
        self.horizontalLayout_6.addWidget(self.Button_stopc, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addWidget(self.frame)
        self.verticalLayout_9.addWidget(self.f_cam_content)
        self.stackedWidget.addWidget(self.page_camera)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_right)
        self.verticalLayout.addWidget(self.frame_content)
        self.frame_down = QtWidgets.QFrame(self.frame_whole)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_down.sizePolicy().hasHeightForWidth())
        self.frame_down.setSizePolicy(sizePolicy)
        self.frame_down.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_down.setStyleSheet("QFrame{\n"
"    background-color: rgb(77, 77, 85);\n"
"    border-bottom-left-radius:30px;\n"
"    border-bottom-right-radius:30px;\n"
"}")
        self.frame_down.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_down.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_down.setObjectName("frame_down")
        self.verticalLayout.addWidget(self.frame_down)
        self.horizontalLayout.addWidget(self.frame_whole)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.Button_exit.clicked.connect(MainWindow.close)
        self.Button_small.clicked.connect(MainWindow.showMinimized)
        self.Button_big.clicked.connect(MainWindow.showMaximized)
        self.Button_normal.clicked.connect(MainWindow.showNormal)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; color:#dcdcdc;\">Yolov5武器装备检测系统</span></p></body></html>"))
        self.choose.setText(_translate("MainWindow", "模型选择"))
        self.comboBox.setItemText(0, _translate("MainWindow", "MSPPF_NAM_yolov5m.pt"))
        self.comboBox.setItemText(1, _translate("MainWindow", "MSPPF_NAM_yolov5s.pt"))
        self.setting.setText(_translate("MainWindow", " Setting"))
        self.input.setText(_translate("MainWindow", "输入选择"))
        self.Button_pic.setText(_translate("MainWindow", "图 像 检 测"))
        self.Button_camera.setText(_translate("MainWindow", "摄 像 头 检 测"))
        self.Button_video.setText(_translate("MainWindow", "视 频 检测"))
        self.input_2.setText(_translate("MainWindow", "Conf"))
        self.input_3.setText(_translate("MainWindow", "Iou"))
        self.result.setText(_translate("MainWindow", "预测结果"))
        self.show_result.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Image detection"))
        self.Button_upload.setText(_translate("MainWindow", "Upload"))
        self.Button_detect.setText(_translate("MainWindow", "Detect"))
        self.label_2.setText(_translate("MainWindow", "Video detection"))
        self.Button_openvid.setText(_translate("MainWindow", "Detect Video"))
        self.Button_stopv.setText(_translate("MainWindow", "Stop detecting"))
        self.label_4.setText(_translate("MainWindow", "Camera detection"))
        self.Button_opencam.setText(_translate("MainWindow", "Open the Camera"))
        self.Button_stopc.setText(_translate("MainWindow", "Stop detecting"))

